services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - inceptionetwork
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wp # needs to access index.php, wp-content ecc.
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql  # Persist database data
    restart: unless-stopped
    networks:
      - inceptionetwork
  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wp
    restart: unless-stopped
    networks:
      - inceptionetwork
    depends_on:
      - mariadb

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
  inceptionetwork:
