services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql  # Persist database data
    restart: unless-stopped

volumes:
  mariadb:
